server:
  servlet:
    context-path: /
    session:
      timeout: 86400s
  forward-headers-strategy: framework

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  flyway:
    locations: classpath:db/h2
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

nocom:
  ssh-tunnel:
    enabled: true
    host-address: nocom
    host-port: 22
    username: dev
    private-key-file: ssh/id_rsa
  authentication:
    debug-users:
      - 'debug:pass'
      - 'root:pass'
    reserved-usernames:
      - 'debug'
      - 'root'
  datasource:
    h2:
      database: ./data
      mode: file
    postgres:
      hostname: localhost
      port: 5432
      database: nocom
      username: nocom
      password: ***REMOVED***

logging:
  level:
    root: INFO
    com.matt.nocom: DEBUG
    com.memorynotfound: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.jdbc: INFO
    org.apache.sshd: INFO
    org.jooq: INFO

